services:
  techtracker:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    container_name: techtracker
    networks:
      - nginx-bridge
    #ports:
      #- "3000:3000"
    tty: true
    restart: unless-stopped
networks:
  nginx-bridge:
    external: true

